# Jekyll config
markdown: redcarpet

# Website config
title:      "Planet"
headline:   "Tout ce qui touche à l'IT dans la région Auvergne !"
footer:     "Planet Clermont'ech regroupe l'ensemble des acteurs du monde IT auvergnat à travers un agenda ouvert."
meta:
    default_author:         "Clermont'ech"
    default_description:    ""
google:
    analytics:              "UA-41697057-2"
insert:
    google-calendar:        "Ajouter à mon agenda Google"
