title:      "Planet Clermont'ech"
headline:   "Tout ce qui touche à l'IT dans la région Auvergne !"
footer:     "Planet Clermont'ech est regroupe l'ensemble des acteurs du monde IT auvergnat à travers un agenda ouvert."
meta:
    default_author:         "Clermont'ech"
    default_description:    ""
google:
    analytics:              "UA-41697057-1"
